server:
  port: 8081

logging:
  level:
    root: info
  file: ${java.io.tmpdir}/${spring.application.name}.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'

spring:
  application:
    name: workflow
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123123
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 8
    max-active: 16
    min-idle: 8
    max-wait: 60000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false